package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"

	"rinha-backend-2026/internal/artifact"
	"rinha-backend-2026/internal/ivf"
	"rinha-backend-2026/internal/mcc"
	"rinha-backend-2026/internal/norm"
	"rinha-backend-2026/internal/vectorizer"
)

type entry struct {
	Request          json.RawMessage `json:"request"`
	ExpectedApproved bool            `json:"expected_approved"`
}

type record struct {
	fastCount   uint8
	fastWorst   int64
	fullCount   uint8
	expectedApp bool
}

func approvedFromCount(c uint8) bool { return float64(c)/5.0 < 0.6 }

func main() {
	art, err := artifact.LoadFromFile("internal/artifact/artifact.bin")
	if err != nil {
		log.Fatalf("load artifact: %v", err)
	}
	K := int(art.NumClusters())
	log.Printf("artifact loaded: N=%d K=%d", art.NumVectors(), K)

	radii := ivf.ComputeRadii(art.Centroids, art.VectorsData, art.ClusterTable, K)
	_ = radii

	normCfg, err := norm.Load()
	if err != nil {
		log.Fatalf("load norm: %v", err)
	}
	mccRisks, err := mcc.Load()
	if err != nil {
		log.Fatalf("load mcc: %v", err)
	}

	tf, err := os.Open("rinha-de-backend-2026/test/test-data.json")
	if err != nil {
		log.Fatalf("open test data: %v", err)
	}
	var top struct {
		Entries []entry `json:"entries"`
	}
	if err := json.NewDecoder(tf).Decode(&top); err != nil {
		log.Fatalf("decode test data: %v", err)
	}
	tf.Close()
	log.Printf("test entries: %d", len(top.Entries))

	clusterTableBytes := serializeClusterTable(art.ClusterTable)
	scratch := &ivf.SearchScratch{
		CentroidDists: make([]int64, K),
	}
	records := make([]record, 0, len(top.Entries))
	parseFails := 0
	for _, e := range top.Entries {
		var payload vectorizer.Payload
		if err := json.Unmarshal(e.Request, &payload); err != nil {
			parseFails++
			continue
		}
		qi, err := vectorizer.VectorizeInt16(&payload, normCfg, mccRisks)
		if err != nil {
			parseFails++
			continue
		}
		fastCnt, fastWorst := ivf.FraudCountFastOnly(
			&qi,
			art.Centroids,
			art.Bboxes,
			clusterTableBytes,
			art.VectorsData,
			scratch,
		)
		fullCnt := ivf.FraudCountFull(
			&qi,
			art.Centroids,
			art.Bboxes,
			clusterTableBytes,
			art.VectorsData,
			scratch,
		)
		records = append(records, record{
			fastCount:   fastCnt,
			fastWorst:   fastWorst,
			fullCount:   fullCnt,
			expectedApp: e.ExpectedApproved,
		})
	}
	log.Printf("processed %d entries (parse_fails=%d)", len(records), parseFails)

	log.Printf("--- per-class breakdown ---")
	for c := uint8(0); c <= 5; c++ {
		var n, mismatchFast, mismatchFull, fixable int
		for _, r := range records {
			if r.fastCount != c {
				continue
			}
			n++
			if approvedFromCount(r.fastCount) != r.expectedApp {
				mismatchFast++
			}
			if approvedFromCount(r.fullCount) != r.expectedApp {
				mismatchFull++
			}
			if approvedFromCount(r.fastCount) != r.expectedApp &&
				approvedFromCount(r.fullCount) == r.expectedApp {
				fixable++
			}
		}
		log.Printf("class=%d n=%-6d fast_wrong=%-4d full_wrong=%-4d fixable_by_escalation=%d",
			c, n, mismatchFast, mismatchFull, fixable)
	}

	thresholds := computeThresholds(records)
	log.Printf("--- chosen thresholds ---")
	totalEscalations := 0
	for c := uint8(0); c <= 5; c++ {
		log.Printf("class=%d threshold=%d", c, thresholds[c])
		for _, r := range records {
			if r.fastCount != c {
				continue
			}
			needEscalate := (c == 2 || c == 3 || c == 4) ||
				(thresholds[c] > 0 && r.fastWorst > thresholds[c])
			if needEscalate {
				totalEscalations++
			}
		}
	}
	log.Printf("expected escalations: %d / %d (%.2f%%)",
		totalEscalations, len(records), 100*float64(totalEscalations)/float64(len(records)))

	fp, fn := 0, 0
	for _, r := range records {
		c := r.fastCount
		escalate := (c == 2 || c == 3 || c == 4) ||
			(thresholds[c] > 0 && r.fastWorst > thresholds[c])
		finalCnt := r.fastCount
		if escalate {
			finalCnt = r.fullCount
		}
		approved := approvedFromCount(finalCnt)
		switch {
		case approved && !r.expectedApp:
			fn++
		case !approved && r.expectedApp:
			fp++
		}
	}
	log.Printf("--- post-calibration projection (oracle = full-K sweep) ---")
	log.Printf("FP=%d FN=%d", fp, fn)

	fmt.Println()
	fmt.Println("// generated by cmd/calibrate — paste into internal/ivf/thresholds.go")
	fmt.Println("var ExtremeWorstThreshold = [6]int64{")
	for c := uint8(0); c <= 5; c++ {
		fmt.Printf("\t/* count=%d */ %d,\n", c, thresholds[c])
	}
	fmt.Println("}")
}

func computeThresholds(records []record) [6]int64 {
	var out [6]int64
	for c := uint8(0); c <= 5; c++ {
		if c == 2 || c == 3 || c == 4 {
			continue
		}
		var fixableWorsts []int64
		for _, r := range records {
			if r.fastCount != c {
				continue
			}
			fastWrong := approvedFromCount(r.fastCount) != r.expectedApp
			fullRight := approvedFromCount(r.fullCount) == r.expectedApp
			if fastWrong && fullRight {
				fixableWorsts = append(fixableWorsts, r.fastWorst)
			}
		}
		if len(fixableWorsts) == 0 {
			continue
		}
		sort.Slice(fixableWorsts, func(i, j int) bool { return fixableWorsts[i] < fixableWorsts[j] })
		out[c] = fixableWorsts[0] - 1
	}
	return out
}

func serializeClusterTable(entries []artifact.ClusterEntry) []byte {
	const entrySz = 8
	buf := make([]byte, len(entries)*entrySz)
	for i, e := range entries {
		off := i * entrySz
		binary.LittleEndian.PutUint32(buf[off:], e.Offset)
		binary.LittleEndian.PutUint32(buf[off+4:], e.Count)
	}
	return buf
}
